### ISSUE TITLE
AttributeError: 'PosixPath' object has no attribute 'read_text'

### ISSUE THREAD

**Issue by domingo13** [F5-Labs/cryptonice#10]
When trying to install it with pip I get:
root@host:~# pip install cryptonice
Collecting cryptonice
  Using cached https://files.pythonhosted.org/packages/c4/eb/5d5df1a5ae9056a90bf5e620684924c7971dccf037e3d2b3578659540f58/cryptonice-0.1.17.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-noio1d/cryptonice/setup.py", line 11, in <module>
        README = (HERE / "README.md").read_text()
    AttributeError: 'PosixPath' object has no attribute 'read_text'

    ----------------------------------------

**Comment by warburtr0n** [comment]
Thanks for taking the time to try out Cryptonice and log this issue! Can you please descibe the system (operating system, version of Python, etc) you are attempting to install this on to?

**Comment by domingo13** [comment]
It was a Ubuntu 18.04 with a mix of python2.7 and python 3.6.9.
I created a new Ubuntu 20.04 where only python 3 is available and it runs perfectly.

**Comment by warburtr0n** [comment]
That's useful feedback, thank you @domingo13. In the short term we will compile a list of currently supported Operating Systems and look at plans to support those that are not.

I am going to close this Issue for now while we fully document which OS's are supported but I'm happy to open this back up when we are able to look at specific issues such as this.
