### ISSUE TITLE
Dependency on pycurl requires libcurl devel packages outside of pip

### ISSUE THREAD

**Issue by vsnine** [F5-Labs/cryptonice#12]
Hello,

I went to install this on a CentOS 7.6 server today for testing and found that it has a dependency outside of pip via pycurl, which I believe is libcurl-devel. I'm waiting for my admin to install the package for me to verify, but it could be worthwhile to mention in any installation guides.

```
$ pip install cryptonice
Collecting cryptonice
  Using cached https://files.pythonhosted.org/packages/ab/5d/a333344eadfa3d357ce94553832ba343a5396ade129c14e0d51665c7c514/cryptonice-0.1.19-py3-none-any.whl
Collecting sslyze>=2.1.4 (from cryptonice)
  Using cached https://files.pythonhosted.org/packages/00/fb/56ccb9c9ab28027f9cedc5b80f3a66a42b73e1310c42eae15da01418c1de/sslyze-2.1.4.tar.gz
Collecting dnspython>=1.16.0 (from cryptonice)
  Using cached https://files.pythonhosted.org/packages/90/49/cb426577c28ca3e35332815b795a99e467523843fc83cc85ca0d6be2515a/dnspython-2.0.0-py3-none-any.whl
Collecting http-client>=0.1.21 (from cryptonice)
  Using cached https://files.pythonhosted.org/packages/94/e5/2e8134353629a91854c50a228f1624e21985aca1abc9d0ef0ce25bf5f389/http_client-0.1.22.tar.gz
Collecting urllib3>=1.25.9 (from cryptonice)
  Using cached https://files.pythonhosted.org/packages/9f/f0/a391d1463ebb1b233795cabfc0ef38d3db4442339de68f847026199e69d7/urllib3-1.25.10-py2.py3-none-any.whl
Collecting ipaddress>=1.0.22pathlib~=1.0.1 (from cryptonice)
  Using cached https://files.pythonhosted.org/packages/c2/f8/49697181b1651d8347d24c095ce46c7346c37335ddc7d255833e7cde674d/ipaddress-1.0.23-py2.py3-none-any.whl
Collecting nassl<2.3.0,>=2.2.0 (from sslyze>=2.1.4->cryptonice)
  Downloading https://files.pythonhosted.org/packages/1c/59/2aa9ab432a09e0814231b52cd2dd030d7b308d7288ffcc8493a2bdb957db/nassl-2.2.0-cp36-cp36m-manylinux1_x86_64.whl (3.1MB)
    100% |████████████████████████████████| 3.1MB 3.3MB/s
Collecting cryptography==2.5 (from sslyze>=2.1.4->cryptonice)
  Using cached https://files.pythonhosted.org/packages/98/71/e632e222f34632e0527dd41799f7847305e701f38f512d81bdf96009bca4/cryptography-2.5-cp34-abi3-manylinux1_x86_64.whl
Collecting tls-parser<1.3.0,>=1.2.0 (from sslyze>=2.1.4->cryptonice)
  Downloading https://files.pythonhosted.org/packages/66/4e/da7f727a76bd9abee46f4035dbd7a4711cde408f286dae00c7a1f9dd9cbb/tls_parser-1.2.2.tar.gz
Collecting dataclasses (from sslyze>=2.1.4->cryptonice)
  Downloading https://files.pythonhosted.org/packages/e1/d2/6f02df2616fd4016075f60157c7a0452b38d8f7938ae94343911e0fb0b09/dataclasses-0.7-py3-none-any.whl
Collecting pycurl (from http-client>=0.1.21->cryptonice)
  Using cached https://files.pythonhosted.org/packages/ef/05/4b773f74f830a90a326b06f9b24e65506302ab049e825a3c0b60b1a6e26a/pycurl-7.43.0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/tmp/pip-install-14reoqxd/pycurl/setup.py", line 234, in configure_unix
        stdout=subprocess.PIPE, stderr=subprocess.PIPE)
      File "/usr/lib64/python3.6/subprocess.py", line 709, in __init__
        restore_signals, start_new_session)
      File "/usr/lib64/python3.6/subprocess.py", line 1344, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'curl-config': 'curl-config'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-14reoqxd/pycurl/setup.py", line 961, in <module>
        ext = get_extension(sys.argv, split_extension_source=split_extension_source)
      File "/tmp/pip-install-14reoqxd/pycurl/setup.py", line 623, in get_extension
        ext_config = ExtensionConfiguration(argv)
      File "/tmp/pip-install-14reoqxd/pycurl/setup.py", line 101, in __init__
        self.configure()
      File "/tmp/pip-install-14reoqxd/pycurl/setup.py", line 238, in configure_unix
        raise ConfigurationError(msg)
    __main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory: 'curl-config': 'curl-config'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-14reoqxd/pycurl/
You are using pip version 10.0.1, however version 20.2b1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by sebastiancapilano** [comment]
I got farther with:

yum -y install python38 python38-devel
yum -y install libcurl-devel
python3 -m venv --system-site-packages cryptonice
source cryptonice/bin/activate
pip install cryptonice

But I'm still having this issue:
(cryptonice) [root ~]# cryptonice f5.com
Traceback (most recent call last):
  File "/root/cryptonice/bin/cryptonice", line 5, in <module>
    from cryptonice.__main__ import main
  File "/root/cryptonice/lib64/python3.8/site-packages/cryptonice/__main__.py", line 1, in <module>
    from cryptonice.scanner import scanner_driver
  File "/root/cryptonice/lib64/python3.8/site-packages/cryptonice/scanner.py", line 6, in <module>
    from cryptonice.modules.gettls import tls_scan
  File "/root/cryptonice/lib64/python3.8/site-packages/cryptonice/modules/gettls.py", line 4, in <module>
    from sslyze import (
  File "/root/cryptonice/lib64/python3.8/site-packages/sslyze/__init__.py", line 25, in <module>
    from sslyze.plugins.scan_commands import ScanCommand, ScanCommandType
  File "/root/cryptonice/lib64/python3.8/site-packages/sslyze/plugins/scan_commands.py", line 10, in <module>
    from sslyze.plugins.certificate_info.implementation import CertificateInfoImplementation
  File "/root/cryptonice/lib64/python3.8/site-packages/sslyze/plugins/certificate_info/implementation.py", line 9, in <module>
    from sslyze.plugins.certificate_info._cert_chain_analyzer import (
  File "/root/cryptonice/lib64/python3.8/site-packages/sslyze/plugins/certificate_info/_cert_chain_analyzer.py", line 17, in <module>
    from sslyze.plugins.certificate_info._certificate_utils import extract_dns_subject_alternative_names, get_common_names
  File "/root/cryptonice/lib64/python3.8/site-packages/sslyze/plugins/certificate_info/_certificate_utils.py", line 1, in <module>
    from _sha256 import sha256
ModuleNotFoundError: No module named '_sha256'

**Comment by vsnine** [comment]
what does pip freeze say about your virtualenv?

**Comment by sebastiancapilano** [comment]
[root@ ~]# source cryptonice/bin/activate
(cryptonice) [root@ ~]# pip freeze
cffi==1.14.0
cryptography==2.9
cryptonice==0.1.19
dnspython==2.0.0
http-client==0.1.22
ipaddress==1.0.23
nassl==3.0.0
pycparser==2.20
pycrypto==2.6.1
pycurl==7.43.0.5
six==1.15.0
sslyze==3.0.8
tls-parser==1.2.2
urllib3==1.25.10

**Comment by michaelf97** [comment]
Hello vsnine. The pycurl dependency must be installed manually as stated in the docs.

https://cryptonice.readthedocs.io/en/latest/intro/install.html#ubuntu

**Comment by warburtr0n** [comment]
I'm pleased to say that I've now updated the docs to show that CentOS 8 is working with Cryptonice:

https://cryptonice.readthedocs.io/en/latest/intro/install.html#centos
