### ISSUE TITLE
AttributeError: 'CipherSuitesScanResult'

### ISSUE THREAD

**Issue by Devasastha** [F5-Labs/cryptonice#21]
$**cryptonice f5.com**
Pre-scan checks
-------------------------------------
Scanning f5.com on port 443...
Analyzing DNS data for f5.com
Fetching additional records for f5.com
f5.com resolves to 107.162.162.40
107.162.162.40:443: OPEN
TLS is available: True
Connecting to port 443 using HTTPS
Reading HTTP headers for www.f5.com
Queueing TLS scans (this might take a little while...)
0
Traceback (most recent call last):
  File "/usr/local/bin/cryptonice", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/cryptonice/__main__.py", line 104, in main
    output_data, hostname = scanner_driver(input_data)
  File "/usr/local/lib/python3.8/dist-packages/cryptonice/scanner.py", line 427, in scanner_driver
    tls_data = tls_scan(ip_address, str_host, commands_to_run, port)
  File "/usr/local/lib/python3.8/dist-packages/cryptonice/modules/gettls.py", line 273, in tls_scan
    **preferred_cipher_suite = ssl2_result.cipher_suite_preferred_by_server
AttributeError: 'CipherSuitesScanResult' object has no attribute 'cipher_suite_preferred_by_server'**

Tried this and getting this error, what is missing here...

**Comment by warburtr0n** [comment]
Thanks for the heads up. SSLyze was recently updated to 4.0.1 which removed a function we make use of. For now, the requirements for Cryptonice have been updated to make use of SSLyze 3.0.8. Over the coming days I'll make sure to fix this dependency issue correctly so that we can benefit from the new version of SSLyze.

**Comment by warburtr0n** [comment]
Note: code has been updated but the Cryptonice library (hosted on pypi.org) has not yet been rebuilt.

**Comment by mepamplona** [comment]
Is there an estimate of when it will be rebuilted to v1.2.6?

**Comment by warburtr0n** [comment]
Hi @mepamplona recently updates to Cryptonice should have resolved this. Can you please try the updated Docker image or the new library (v.1.3.7.0) by running command 

`pip3 install --upgrade cryptonice`

Please feel free to re-open this issue if you're still having issues.
