### ISSUE TITLE
Name or service not known (from docker)

### ISSUE THREAD

**Issue by coobr01** [F5-Labs/cryptonice#25]
against echo.epa.gov

socket.gaierror: [Errno -2] Name or service not known

**Comment by warburtr0n** [comment]
Sorry for the delay @coobr01 

There have been a substantial number of bug fixes recently and we're currently on version 1.3.7.0 of the library. A new Docker build also exists for this version so could I ask you to please try again?

I've just tried with the follow command and it's worked okay:

`docker run --rm -it f5labs/cryptonice echo.epa.gov --tls all`
