### ISSUE TITLE
Issue with Docker on Raspberry PI 4

### ISSUE THREAD

**Issue by ny4i** [F5-Labs/cryptonice#28]
docker run f5labs/cryptonice www.f5.com
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
standard_init_linux.go:219: exec user process caused: exec format error

**Comment by warburtr0n** [comment]
Sorry for the delay @ny4i 

Since we're such a small development team it's unlikely we'll be able to dedicate resources to porting this to the ARM platform. We'd be delighted if a member of the community was able to, however.
