### ISSUE TITLE
Update help to include volume/mount instructions

### ISSUE THREAD

**Issue by coobr01** [F5-Labs/cryptonice#38]
Can someone please update the docker related help to include instructions for how to mount or use volumes to get to the json output?

**Comment by warburtr0n** [comment]
Hi @coobr01 

Thankfully I'd implemented some updates last week to allow Cryptonice to write JSON outputs to any folder. This is done using the --json_path parameter. 

So, in order for Docker to output to a folder, use the following syntax:

`docker run --rm -it --volume //c/scratch:/results f5labs/cryptonice www.f5.com --json_out --json_path /results`

This maps my local C:\Scratch folder to a directory called /results within the container.

I've added brief instructions on the Cryptonice homepage and also on the ReadTheDocs pages but let me know if more examples would be useful.

**Comment by coobr01** [comment]
@warburtr0n thanks, worked perfectly!
